// Copyright 2026 mjbots Robotic Systems, LLC.  info@mjbots.com
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

/// @file
///
/// Compile-time generated, type-erased descriptions of serializable
/// types.
///
/// The classic approach of instantiating every archive for every
/// serializable structure results in a large amount of code per
/// structure and per field.  Instead, each type gets a small constant
/// TypeDescriptor, and a single non-template interpreter (see
/// serializable_handler.cc) implements all operations in terms of
/// those descriptors.
///
/// The fields of a structure are enumerated by instantiating its
/// Serialize method exactly once, with an archive that makes one
/// out-of-line call per field.
///
/// If an mjlib::base::IsEnum map() is constexpr, its entries are
/// stored in a constant table rather than generated by code.
///
/// All field types must be one of: bool, integral types of 1, 2, 4,
/// or 8 bytes, float, double, enumerations declared with
/// mjlib::base::IsEnum, std::array, std::optional, nested serializable
/// structures, or types with an mjlib::base::ExternalSerializer.

#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <new>
#include <optional>
#include <tuple>
#include <type_traits>
#include <utility>

#include "mjlib/base/visitor.h"

namespace mjlib {
namespace micro {

enum class TypeKind : uint8_t {
  kBool,
  kInt8,
  kInt16,
  kInt32,
  kInt64,
  kUInt8,
  kUInt16,
  kUInt32,
  kUInt64,
  kFloat32,
  kFloat64,

  kEnum,
  kArray,
  kOptional,
  kStruct,
  kExternal,
};

/// All descriptors begin with this, and may be downcast based on the
/// value of 'kind'.  Scalar types need nothing more.
struct TypeDescriptor {
  TypeKind kind;
};

using DefaultCallback = void (*)(void* context, void* object);

/// Invoke the callback with a pointer to a temporary default
/// constructed instance of some type.
using WithDefaultFunction = void (*)(DefaultCallback, void* context);

class EnumEntryVisitor {
 public:
  virtual void Entry(int64_t value, const char* name) = 0;

 protected:
  ~EnumEntryVisitor() {}
};

struct EnumEntry {
  const char* name;
  /// The value, truncated to 32 bits.  It is sign extended if the
  /// underlying type is signed.
  uint32_t value;
};

struct EnumDescriptor : TypeDescriptor {
  TypeKind underlying;
  uint16_t count;

  /// If the IsEnum map can be evaluated at compile time, this is a
  /// constant table of 'count' entries.
  const EnumEntry* entries;

  /// Otherwise, this is non-null and used instead.
  void (*visit_entries)(EnumEntryVisitor&);
};

struct ArrayDescriptor : TypeDescriptor {
  uint16_t size;
  uint16_t stride;
  const TypeDescriptor* element;

  /// Only non-null for elements which are not scalars or
  /// enumerations.  Used to provide default values for schemas.
  WithDefaultFunction element_default;
};

struct OptionalDescriptor : TypeDescriptor {
  const TypeDescriptor* element;
  void* (*get)(void* optional);
  /// Return the contained value, first value-initializing it if the
  /// optional was empty.
  void* (*get_or_emplace)(void* optional);
  /// Value-initialize the contained value, discarding any previous
  /// one.
  void* (*emplace)(void* optional);
  WithDefaultFunction element_default;
};

class FieldVisitor {
 public:
  virtual void Field(const char* name, void* value,
                     const TypeDescriptor* type) = 0;

 protected:
  ~FieldVisitor() {}
};

struct StructDescriptor : TypeDescriptor {
  void (*visit_fields)(void* object, FieldVisitor&);
};

class ValueVisitor {
 public:
  virtual void Value(void* value, const TypeDescriptor* type) = 0;

 protected:
  ~ValueVisitor() {}
};

struct ExternalDescriptor : TypeDescriptor {
  void (*visit)(void* object, ValueVisitor&);
};

/// Report one field to a visitor.  This is out of line so that each
/// field in a field function costs as little code as possible.
void EmitField(FieldVisitor&, const char* name, void* value,
               const TypeDescriptor*);

template <typename T>
constexpr const TypeDescriptor* GetTypeDescriptor();

namespace detail {

template <typename T>
struct IsStdArray : std::false_type {};

template <typename T, std::size_t N>
struct IsStdArray<std::array<T, N>> : std::true_type {};

template <typename T>
struct IsStdOptional : std::false_type {};

template <typename T>
struct IsStdOptional<std::optional<T>> : std::true_type {};

template <typename T>
inline constexpr bool kAlwaysFalse = false;

template <typename T>
using ValueTypeOf = std::remove_cv_t<
  std::remove_pointer_t<decltype(std::declval<const T&>().value())>>;

template <typename T>
constexpr TypeKind ScalarKind() {
  if constexpr (std::is_same_v<T, bool>) {
    return TypeKind::kBool;
  } else if constexpr (std::is_integral_v<T>) {
    static_assert(sizeof(T) == 1 || sizeof(T) == 2 ||
                  sizeof(T) == 4 || sizeof(T) == 8);
    constexpr bool s = std::is_signed_v<T>;
    if constexpr (sizeof(T) == 1) {
      return s ? TypeKind::kInt8 : TypeKind::kUInt8;
    } else if constexpr (sizeof(T) == 2) {
      return s ? TypeKind::kInt16 : TypeKind::kUInt16;
    } else if constexpr (sizeof(T) == 4) {
      return s ? TypeKind::kInt32 : TypeKind::kUInt32;
    } else {
      return s ? TypeKind::kInt64 : TypeKind::kUInt64;
    }
  } else if constexpr (std::is_same_v<T, float>) {
    return TypeKind::kFloat32;
  } else if constexpr (std::is_same_v<T, double>) {
    return TypeKind::kFloat64;
  } else {
    static_assert(kAlwaysFalse<T>,
                  "type is not supported by mjlib::micro serialization");
    return TypeKind::kBool;
  }
}

template <typename T>
constexpr bool IsLeaf() {
  return !base::IsNativeSerializable<T>() &&
      !base::IsExternalSerializable<T>() &&
      !IsStdArray<T>::value &&
      !IsStdOptional<T>::value;
}

/// Default initialize a T in the given storage.  This is kept out of
/// line so that each type's constructor is only emitted once, no
/// matter how many ways a default instance is needed.
template <typename T>
__attribute__((noinline)) void ConstructDefault(void* storage) {
  ::new (storage) T;
}

template <typename T>
inline constexpr bool kIsTrivial =
    std::is_trivially_copyable_v<T> && std::is_trivially_destructible_v<T>;

/// Equivalent to 'new (storage) T()'.
template <typename T>
void ConstructValue(void* storage) {
  if constexpr (kIsTrivial<T>) {
    // Value initialization is zero initialization followed by default
    // initialization for anything without a user-provided default
    // constructor.
    std::memset(storage, 0, sizeof(T));
    ConstructDefault<T>(storage);
  } else {
    ::new (storage) T();
  }
}

template <typename T>
void WithValueInitialized(DefaultCallback callback, void* context) {
  alignas(T) unsigned char storage[sizeof(T)];
  ConstructValue<T>(storage);
  T* const object = std::launder(reinterpret_cast<T*>(storage));
  callback(context, object);
  object->~T();
}

template <typename T>
void WithDefaultInitialized(DefaultCallback callback, void* context) {
  alignas(T) unsigned char storage[sizeof(T)];
  ConstructDefault<T>(storage);
  T* const object = std::launder(reinterpret_cast<T*>(storage));
  callback(context, object);
  object->~T();
}

/// Equivalent to '*object = T()'.
template <typename T>
void AssignValue(void* object) {
  if constexpr (kIsTrivial<T>) {
    ConstructValue<T>(object);
  } else {
    *static_cast<T*>(object) = T();
  }
}

template <typename T>
concept ConstexprEnumMap = requires {
  typename std::integral_constant<
    std::size_t, base::IsEnum<T>::map().size()>;
};

template <typename T>
constexpr auto MakeEnumEntries() {
  constexpr auto map = base::IsEnum<T>::map();
  std::array<EnumEntry, map.size()> result = {};
  for (std::size_t i = 0; i < map.size(); i++) {
    result[i] = EnumEntry{
      map[i].second,
      static_cast<uint32_t>(static_cast<int64_t>(map[i].first))};
  }
  return result;
}

template <typename T>
inline constexpr auto kEnumEntries = MakeEnumEntries<T>();

template <typename T>
void VisitEnumEntries(EnumEntryVisitor& visitor) {
  for (const auto& pair : base::IsEnum<T>::map()) {
    visitor.Entry(static_cast<int64_t>(pair.first), pair.second);
  }
}

template <typename T>
void* OptionalGet(void* ptr) {
  auto& optional = *static_cast<std::optional<T>*>(ptr);
  return optional ? &*optional : nullptr;
}

template <typename T>
void* OptionalGetOrEmplace(void* ptr) {
  auto& optional = *static_cast<std::optional<T>*>(ptr);
  if (!optional) { optional.emplace(); }
  return &*optional;
}

template <typename T>
void* OptionalEmplace(void* ptr) {
  return &static_cast<std::optional<T>*>(ptr)->emplace();
}

template <typename T>
void VisitExternal(void* object, ValueVisitor& visitor) {
  base::ExternalSerializer<T> serializer;
  serializer.Serialize(static_cast<T*>(object), [&](const auto& nvp) {
      using U = ValueTypeOf<std::decay_t<decltype(nvp)>>;
      visitor.Value(const_cast<U*>(nvp.value()), GetTypeDescriptor<U>());
    });
}

/// The field function archive: one out-of-line call per field.
class FieldArchive {
 public:
  explicit FieldArchive(FieldVisitor& visitor) : visitor_(visitor) {}

  template <typename NameValuePair>
  void Visit(const NameValuePair& nvp) {
    using U = ValueTypeOf<NameValuePair>;
    EmitField(visitor_, nvp.name(), const_cast<U*>(nvp.value()),
              GetTypeDescriptor<U>());
  }

 private:
  FieldVisitor& visitor_;
};

template <typename T>
void VisitFields(void* object, FieldVisitor& visitor) {
  FieldArchive archive(visitor);
  static_cast<T*>(object)->Serialize(&archive);
}


template <typename T>
constexpr auto MakeDescriptor() {
  if constexpr (base::IsNativeSerializable<T>()) {
    return StructDescriptor{{TypeKind::kStruct}, &VisitFields<T>};
  } else if constexpr (base::IsExternalSerializable<T>()) {
    return ExternalDescriptor{{TypeKind::kExternal}, &VisitExternal<T>};
  } else if constexpr (base::IsEnum<T>::value) {
    using Map = decltype(base::IsEnum<T>::map());
    using Underlying = std::underlying_type_t<T>;
    if constexpr (ConstexprEnumMap<T> && sizeof(Underlying) <= 4) {
      return EnumDescriptor{
        {TypeKind::kEnum},
        ScalarKind<Underlying>(),
        static_cast<uint16_t>(std::tuple_size_v<Map>),
        kEnumEntries<T>.data(),
        nullptr,
      };
    } else {
      return EnumDescriptor{
        {TypeKind::kEnum},
        ScalarKind<Underlying>(),
        static_cast<uint16_t>(std::tuple_size_v<Map>),
        nullptr,
        &VisitEnumEntries<T>,
      };
    }
  } else if constexpr (IsStdArray<T>::value) {
    using E = typename T::value_type;
    static_assert(std::tuple_size_v<T> < 65536);
    static_assert(sizeof(E) < 65536);
    WithDefaultFunction element_default = nullptr;
    if constexpr (!IsLeaf<E>()) {
      element_default = &WithValueInitialized<E>;
    }
    return ArrayDescriptor{
      {TypeKind::kArray},
      static_cast<uint16_t>(std::tuple_size_v<T>),
      static_cast<uint16_t>(sizeof(E)),
      GetTypeDescriptor<E>(),
      element_default,
    };
  } else if constexpr (IsStdOptional<T>::value) {
    using E = typename T::value_type;
    WithDefaultFunction element_default = nullptr;
    if constexpr (!IsLeaf<E>()) {
      element_default = &WithDefaultInitialized<E>;
    }
    return OptionalDescriptor{
      {TypeKind::kOptional},
      GetTypeDescriptor<E>(),
      &OptionalGet<E>,
      &OptionalGetOrEmplace<E>,
      &OptionalEmplace<E>,
      element_default,
    };
  } else {
    return TypeDescriptor{ScalarKind<T>()};
  }
}

template <typename T>
struct Descriptor {
  static constexpr auto value = MakeDescriptor<T>();
};

}  // namespace detail

template <typename T>
constexpr const TypeDescriptor* GetTypeDescriptor() {
  return &detail::Descriptor<std::remove_cv_t<T>>::value;
}

}
}
